Judging page
ScottyLabs/tartanhacks-judging pull request #17
Opened 2023-01-26 04:50 UTC by pm3512

# Description

Adds judging page at /judging

Closes #3

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-01-27 18:36 UTC, gramliu commented
![image](https://user-images.githubusercontent.com/24856195/215167342-e9ed09d1-be7f-4bb9-bf42-b0f4d0a8a7c2.png)

Can we make the description text slightly smaller?

2023-01-27 18:40 UTC, gramliu commented
![image](https://user-images.githubusercontent.com/24856195/215168070-693f6014-81d0-4688-8499-228becc7c89b.png)

Great job with the colors here. One problem I'm seeing though is that even though you have instructions, it's not immediately intuitive for users (who might not be super tech savvy) to do this. Could you try making the selection use radio buttons instead?

2023-01-31 03:26 UTC, gramliu requested changes

2023-01-31 03:26 UTC, gramliu commented on src/components/VotingList.tsx
> +  const inactiveColor = "#000000";
Can we move these to `tailwind.config.cjs`?

See https://tailwindcss.com/docs/theme

2023-01-31 03:26 UTC, gramliu commented on src/components/VotingList.tsx
> +                    className="text-blue-600 focus:ring-blue-500 dark:focus:ring-blue-600 border-gray-300 bg-gray-100 focus:ring-2 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800"
Is the box around the radio button intended behavior?
![image](https://user-images.githubusercontent.com/24856195/215655318-5e66c40c-ad65-45cd-88b8-efbb9e11f21e.png)

2023-01-31 03:26 UTC, gramliu commented on src/components/VotingList.tsx
> +  const inactiveColor = "#000000";
By moving it to the tailwind config, we can assign the colors using tailwind classes

2023-01-31 03:30 UTC, pm3512 commented on src/components/VotingList.tsx
> +                    className="text-blue-600 focus:ring-blue-500 dark:focus:ring-blue-600 border-gray-300 bg-gray-100 focus:ring-2 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800"
What browser are you using? It looks like this for me on google and firefox
![image](https://user-images.githubusercontent.com/42977183/215655845-56512c0a-8391-43c8-8b28-7e72c3c90294.png)

2023-01-31 03:35 UTC, gramliu commented on src/components/VotingList.tsx
> +                    className="text-blue-600 focus:ring-blue-500 dark:focus:ring-blue-600 border-gray-300 bg-gray-100 focus:ring-2 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800"
I'm using Microsoft edge which should have similar behavior to chrome. It's fine then if it works for chrome and firefox

2023-01-31 03:35 UTC, gramliu commented on src/components/VotingList.tsx
> +                    className="text-blue-600 focus:ring-blue-500 dark:focus:ring-blue-600 border-gray-300 bg-gray-100 focus:ring-2 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800"
Anyway, most people will be viewing this on mobile

2023-01-31 03:48 UTC, gramliu commented
[![LGTM](https://lgtm.lol/p/9)](https://lgtm.lol/i/9)

2023-01-31 03:48 UTC, gramliu approved these changes

2023-01-31 03:51 UTC, merged